# This is a basic workflow to help you get started with Actions

name: Java CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout to branch
        uses: actions/checkout@v2

      # Setup JDK
      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          java-version: '8'
          distribution: 'adopt'

      # print the info of cwd
      - name: Hello
        run: |
          pwd
          ls

      - name: Change gradlew permissions
        run: chmod +x ./gradlew

      # Build all .jars
      - name: Run gradlew
        run: |
          ./gradlew jar
          ./gradlew sourcesJar
          ./gradlew javadocJar

      - name: Publish
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew publish

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: build/libs/
